### ISSUE TITLE
Got an unexpected keyword argument 'sparse' when executing AudioTempoMatch

### ISSUE THREAD

**Issue by rodsott** [christian-byrne/audio-separation-nodes-comfyui#5]
When running the remix-songs.json file, it gave me this error:

`Error occurred when executing AudioTempoMatch:

beat_track() got an unexpected keyword argument 'sparse'

File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
res_value = old_func(*final_args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "X:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\audio-separation-nodes-comfyui\src\tempo_match.py", line 32, in main
tempo_1 = estimate_tempo(waveform_1, input_sample_rate_1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "X:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\audio-separation-nodes-comfyui\src\utils.py", line 90, in estimate_tempo
tempo, _ = librosa.beat.beat_track(
^^^^^^^^^^^^^^^^^^^^^^^^
File "X:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
return f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^`

Any idea @christian-byrne ? Please let me know which info you need from my side.

Thanks in advance,

RoD

**Comment by christian-byrne** [comment]
Hello RoD. Can you verify that you have `librosa` version `0.10.2` or higher? You can check by running:

```batch
pip show librosa
```

If the version you have is behind `0.10.2` try

```batch
pip install librosa
```

Let me know if that works, thanks.

**Comment by rodsott** [comment]
Hi @christian-byrne , Thank you for your feedback!

Yes, I was with librosa 0.9.2.dist. Just removed it and installed the latest 0.10.2. Now the workflow worked until the end, but gave me the following error in the console, which wasn`t happening before:

`Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054]`

Any clue on what could be giving me this?

Thanks in advance!

RoD

**Comment by christian-byrne** [comment]
> Hi @christian-byrne , Thank you for your feedback!
> 
> Yes, I was with librosa 0.9.2.dist. Just removed it and installed the latest 0.10.2. Now the workflow worked until the end, but gave me the following error in the console, which wasn`t happening before:
> 
> `Exception in callback _ProactorBasePipeTransport._call_connection_lost(None) handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)> Traceback (most recent call last): File "asyncio\events.py", line 84, in _run File "asyncio\proactor_events.py", line 165, in _call_connection_lost ConnectionResetError: [WinError 10054]`
> 
> Any clue on what could be giving me this?
> 
> Thanks in advance!
> 
> RoD

No problem, happy to help. 

For the new error, it seems to be related to an issue with the `aiohttp` backend on Windows . Can you try to run just the default workflow and see if it works? Also, are you able to share the full log output?

**Comment by rodsott** [comment]
Sure, it works but still gives that error in the end.. 

https://github.com/user-attachments/assets/940534d4-7978-4237-960a-41a25468b329

it give this "An existing connection was forced to be canceled by the remote host". I used to have a similar one when I tried some LLM to connect to local Ollama.

**Comment by christian-byrne** [comment]
> Sure, it works but still gives that error in the end..
> 
>  NVIDIA_Share_Q676xKkFjp.mp4 
> it give this "An existing connection was forced to be canceled by the remote host". I used to have a similar one when I tried some LLM to connect to local Ollama.

I think the issue is caused by another extension like Mixlab or ComfyUI-Manager which creates network connections. If you click the `Load Default` button in the menu and try to run the workflow does it still happen?

**Comment by rodsott** [comment]
btw, if this can help, I`m running the portable Comfy with the following setup:

Platform: Windows 10
Python version: 3.11.8
pytorch version: 2.3.0+cu118
xformers version: 0.0.26.post1+cu118

With both CUDA Runtime and Development 11.8 modules installed on windows.

The only warning I have on my console, but this is old and never managed to fix is:

Warn!: From X:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

**Comment by christian-byrne** [comment]
> btw, if this can help, I`m running the portable Comfy with the following setup:
> 
> Platform: Windows 10 Python version: 3.11.8 pytorch version: 2.3.0+cu118 xformers version: 0.0.26.post1+cu118
> 
> With both CUDA Runtime and Development 11.8 modules installed on windows.
> 
> The only warning I have on my console, but this is old and never managed to fix is:
> 
> _Warn!: From X:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead._
> 
> I'm using tf_keras 2.16.0, but last week they released the 2.17.0 but didn't updated it yet. =)
> 
> Which **protobuf** you`re using?

Thanks for the extra details! It sounds like other users have seen this error too. It seems the connection gets closed, this could be due to:

- Temporary network blips
- Multiple ComfyUI tabs/windows
- Firewall or antivirus software

I'm not sure if this is the main connection or from another extension, or whether the connection is re-established. Are you able to keep using Comfy after that error occurs or does the program crash completely?
