### ISSUE TITLE
Separating more instruments

### ISSUE THREAD

**Issue by drelabre** [christian-byrne/audio-separation-nodes-comfyui#8]
The audio separation node have "Bass, Drums, Other, Vocals", but is there a away to define more instruments, like piano?

**Comment by christian-byrne** [comment]
It is not currently possible with these nodes.

The model used by the audio separation node is **Hybrid Demucs** [[Défossez, 2021](https://pytorch.org/audio/main/references.html#id50)] trained on both training and test sets of MUSDB-HQ [[Rafii et al., 2019](https://pytorch.org/audio/main/references.html#id47)]. The model separates sounds into the categories of Bass, Drums, Other, and Vocals, which is standard (see [Models Comparison](https://paperswithcode.com/sota/music-source-separation-on-musdb18)).

The models that aim to separate arbitrary sounds (as opposed to predefined categories) are less consistent and come with many trade-offs. For that reason, I don't think it would be worth implementing any of them yet. Maybe I am wrong about that.

In any case, if you really need to separate piano, I'd suggest searching for *query-based sound separation* models like https://github.com/Audio-AGI/AudioSep
